accounts/urls.py
from django.urls import path, include
from accounts import views as views

# ________________________________________________

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    # api-v1
    path('api/v1/', include('accounts.api.v1.urls', namespace='api-v1'), name='api-v1'),
]

# ________________________________________________

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# ________________________________________________

# swagger config
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

# ________________________________________________

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls', namespace='accounts'), name='accounts'),
    path("", include('todos.urls', namespace='todos'), name='todos'),
    # Basic Auth for DRF
    path("api-auth/", include("rest_framework.urls")),
    # swagger
    path(
        'swagger/outout.json/',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json',
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui',
    ),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todos/api/v1/urls.py
from django.urls import path, include
from .views import TodoListApiView, TodoDetailsApiView, get_weathermap

# ________________________________________________

app_name = 'api-v1'

urlpatterns = [
    path('todo/list/', TodoListApiView.as_view(), name='todo-list'),
    path('todo/<int:pk>/', TodoDetailsApiView.as_view(), name='todo-details'),
    # weather api
    path('weather/tehran/', get_weathermap, name='get-weather'),
]

# ________________________________________________

todos/urls.py
from django.urls import path, include
from todos import views as views

# ________________________________________________

app_name = 'todos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('todolist/', views.TodoList.as_view(), name='todolist'),
    path('create-todo/', views.CreateTodoView.as_view(), name='create-todo'),
    path('delete-todo/<int:pk>/', views.DeletodoView.as_view(), name='delete-todo'),
    path('update-todo/<int:pk>/', views.UpdateTodoView.as_view(), name='update-todo'),
    path(
        'complate-todo/<int:pk>/',
        views.ComplateTodoView.as_view(),
        name='complate-todo',
    ),
    # api-v1
    path(
        'todos/api/v1/', include('todos.api.v1.urls', namespace='api-v1'), name='api-v1'
    ),
]

# ________________________________________________

todos/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime

# ________________________________________________


class Todo(models.Model):
    title = models.CharField(max_length=250, verbose_name=_('عنوان تسک'))
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_('تاریخ ایجاد')
    )
    update_date = models.DateTimeField(auto_now=True, verbose_name=_('تاریخ ویرایش'))
    published_date = models.DateTimeField(
        default=datetime.now, verbose_name=_('تاریخ انتشار')
    )
    is_active = models.BooleanField(default=True, verbose_name=_('فعال/غیرفعال'))
    is_done = models.BooleanField(default=False, verbose_name=_('انجام شده'))
    author = models.ForeignKey(
        "accounts.CustomUser",
        verbose_name=_("نویسنده"),
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'تسک'
        verbose_name_plural = 'تسک ها'


# ________________________________________________

todos/forms.py
from django import forms
from .models import Todo

# ________________________________________________


class TodoForm(forms.ModelForm):
    title = forms.CharField(
        max_length=250,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control me-2",
                "placeholder": "تسک جدید را وارد کنید...",
            }
        ),
    )

    class Meta:
        model = Todo
        fields = ['title']


# ________________________________________________

todos/api/v1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import generics
from rest_framework import permissions
from .serializers import TodoSerializer
from rest_framework.response import Response
from rest_framework import status
from ...models import Todo
from .permissions import IsOwnerOrReadOnly
import requests
from rest_framework.decorators import api_view
from django.views.decorators.cache import cache_page

# ________________________________________________


class TodoListApiView(generics.ListCreateAPIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = TodoSerializer
    queryset = Todo.objects.filter(is_active=True)

    def get(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_queryset(), many=True)
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        ser_data = self.get_serializer(data=request.data)
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(data=ser_data.data, status=status.HTTP_201_CREATED)


# ________________________________________________


class TodoDetailsApiView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [permissions.IsAuthenticated, IsOwnerOrReadOnly]
    serializer_class = TodoSerializer
    queryset = Todo.objects.filter(is_active=True)
    lookup_field = 'pk'
    lookup_url_kwarg = 'todo-details'

    def get_object(self):
        obj = get_object_or_404(self.get_queryset(), pk=self.kwargs['pk'])
        return obj

    def get(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_object())
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def put(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_object(), data=request.data)
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def patch(self, request, *args, **kwargs):
        ser_data = self.get_serializer(
            instance=self.get_object(), data=request.data, partial=True
        )
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(data=ser_data.data, status=status.HTTP_200_OK)


# ________________________________________________

# Weather Api
# ===========

@api_view(['GET'])
@cache_page(key_prefix='weather_tehran', timeout=60 * 20)
def get_weathermap(request):
    """getting weather api at Tehran City"""

    params = {'q': 'Tehran', 'lang': 'fa', 'appid': '4a8e6acb730d122b707e6bb73b7c1cfb'}
    response = requests.get('https://api.openweathermap.org/data/2.5/weather?', params)

    if response.status_code == 200:
        data = response.json()
        return Response(data=data, status=status.HTTP_200_OK)
    return Response(
        data={'details': 'page is not Found'}, status=status.HTTP_404_NOT_FOUND
    )


# ________________________________________________

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.list import ListView
from django.views import View
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Todo
from .forms import TodoForm
from django.urls import reverse_lazy
from django.http import HttpResponseNotFound

# ________________________________________________


class IndexView(TemplateView):
    template_name = 'todos/index.html'


# ________________________________________________


class TodoList(LoginRequiredMixin, ListView):
    template_name = 'todos/todo_list.html'
    context_object_name = 'todos'

    def get_queryset(self):
        return Todo.objects.filter(author=self.request.user, is_active=True)


# ________________________________________________


class CreateTodoView(LoginRequiredMixin, FormView):
    template_name = 'todos/todo_create.html'
    form_class = TodoForm
    success_url = reverse_lazy('todos:todolist')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)


# ________________________________________________

# class DeletodoView(LoginRequiredMixin,DeleteView):        # problem - Error
#     model = Todo
#     context_object_name = 'todo'
#     success_url = reverse_lazy('todos:todolist')

#     def get(self, request, *args, **kwargs):
#         return self.post(request, *args, **kwargs)

#     def get_queryset(self):
#         return self.model.objects.filter(author=self.request.user)

# ------------------------------


class DeletodoView(LoginRequiredMixin, View):
    success_url = reverse_lazy('todos:todolist')

    def get(self, request, *args, **kwargs):
        todo = get_object_or_404(Todo, pk=self.kwargs['pk'])

        if todo.author == request.user:
            todo.delete()
            return redirect(self.success_url)
        return HttpResponseNotFound(content="صفحه موردنظر وجود ندارد")


# ________________________________________________


class UpdateTodoView(LoginRequiredMixin, UpdateView):
    template_name = 'todos/todo_update.html'
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todos:todolist')

    def get_queryset(self):
        """User permission for change object"""
        return Todo.objects.filter(author=self.request.user, is_active=True)


# ________________________________________________


class ComplateTodoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        todo = get_object_or_404(Todo, pk=self.kwargs['pk'])

        if todo.author != request.user:
            return HttpResponseNotFound(content="صفحه موردنظر وجود ندارد")

        if not todo.is_done:
            todo.is_done = True
            todo.save()
        else:
            todo.is_done = False
            todo.save()

        return redirect('todos:todolist')


# ________________________________________________

templates/todos/index.html
{% extends 'main_template.html' %}


{% block title %}
    home
{% endblock title %}
    


{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="#">📝 Todo App</a>
            <a class="btn btn-sm btn-primary" href="{% url 'todos:api-v1:get-weather' %}">نمایش آب و هوا</a> 
            {% if user.is_authenticated %}
                <div>
                    <a class="btn btn-sm btn-outline-light" href="{% url 'todos:todolist' %}">لیست تسک ها</a>
                    <a class="btn btn-sm btn-outline-light" href="{% url 'accounts:logout' %}">خروج</a>
                </div>
                {% else %}
                <div>
                    <a class="btn btn-sm btn-outline-light" href="{% url 'todos:todolist' %}">لیست تسک ها</a>
                    <a class="btn btn-sm btn-outline-light" href="{% url 'accounts:login' %}">ورود</a>
                </div>
            {% endif %} 
        </div>
    </nav>

    <div class="container">
        <!-- محتوا اینجا لود می‌شود -->
    </div>
{% endblock content %}
    

templates/todos/todo_create.html
    <form class="d-flex mb-3" method="post" action="{% url 'todos:create-todo' %}">
        {% csrf_token %}
        {{form.title}}
        <button type="submit" class="btn btn-success"><i class="bi bi-plus-lg"></i> افزودن</button>
    </form>

templates/todos/todo_list.html
{% extends 'main_template.html' %}
{% load render_partial %}

{% block title %}
    Todo List
{% endblock title %}
    


{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">لیست تسک‌ها</h5>
                </div>
                <div class="card-body">
                    <!-- افزودن تسک -->
                    {% render_partial 'todos:create-todo' %}
                    
                    <!-- جدول تسک‌ها -->
                    <table class="table table-hover align-middle">
                        <thead>
                            <tr>
                                <th>تسک</th>
                                <th class="text-center">وضعیت</th>
                                <th class="text-end">عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for todo in todos %}
                                <tr>
                                    <td id="task1">{{todo.title}}</td>
                                    <td class="text-center">
                                        
                                        {% if todo.is_done %}
                                            <span class="badge bg-success">انجام شده</span>
                                            {% else %}
                                            <span class="badge bg-warning">در حال انجام</span>
                                        {% endif %}
                                            
                                    </td>
                                    <td class="text-end">
                                        <a href="{% url 'todos:update-todo' todo.pk %}" class="btn btn-sm btn-outline-primary"><i
                                                class="bi bi-pencil-square"></i></a>
                                        <button type="button" class="btn btn-sm btn-outline-success"
                                            onclick="completeTask('task1')">
                                            <a style="text-decoration:none;color: inherit;" href="{% url 'todos:complate-todo' todo.pk %}"><i class="bi bi-check2-circle"></i></a>
                                        </button>

                                        <button type="button" class="btn btn-sm btn-outline-danger"
                                            onclick="deleteTask(this)">
                                            <a style="text-decoration:none;color: inherit;" href="{% url 'todos:delete-todo' todo.pk %}">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                            
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        function completeTask(id) {
            const el = document.getElementById(id);
            if (el) {
                el.classList.toggle("completed");
            }
        }
        function deleteTask(btn) {
            const row = btn.closest("tr");
            row.remove();
        }
    </script>
{% endblock content %}
    

templates/todos/todo_update.html
{% extends 'main_template.html' %}

{% block title %}
    Todo Update
{% endblock title %}
    


{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-warning text-dark">
                    <h5>ویرایش تسک</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label">متن تسک</label>
                            {{form.title}}
                        </div>
                        <button type="submit" class="btn btn-warning">ذخیره تغییرات</button>
                        <a href="{% url 'todos:todolist' %}" class="btn btn-secondary">بازگشت</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
    